#%RAML 1.0 Trait
 usage: Apply this trait to enforce          client-id-identification
 headers:
   client_id:
     type: string
     description: client_id to authenticate to system api
     required: true
   client_secret:
     type: string
     description: client_secret to authenticate to system api
     


